[Unit]
Name = "kanata"
Description = "Software keyboard remapper"

[Service]
Kind = "Simple"
Restart = "Never"

[Service.ExecStart]
Executable = "kanata.exe"
Arguments = [
    "-c",
    "C:/Users/DaNub/.config/kanata/main.kbd",
]

[Service.Healthcheck.Process]
DelaySec = 1
